# Generated by Django 4.0 on 2022-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SundayServicesVespers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.IntegerField()),
                ('gv1', models.TextField()),
                ('gv2', models.TextField()),
                ('gv3', models.TextField()),
                ('gv4', models.TextField()),
                ('gv5', models.TextField()),
                ('gv6', models.TextField()),
                ('gv7', models.TextField()),
                ('gv8', models.TextField()),
                ('gv9', models.TextField()),
                ('gv10', models.TextField()),
                ('dogmatic', models.TextField()),
                ('st1', models.TextField()),
                ('st2', models.TextField()),
                ('st3', models.TextField()),
                ('st4', models.TextField()),
                ('bg_st', models.TextField()),
            ],
        ),
    ]
