# Generated by Django 4.0 on 2022-02-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0003_alter_sundayservicesvespers_bg_st_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayServicesMatins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tropar', models.TextField(verbose_name='Тропарь')),
                ('bg_tr', models.TextField(verbose_name='Богородичен тропаря')),
                ('sed1a', models.TextField(verbose_name='По первой кафизме седален (а)')),
                ('sed1b', models.TextField(verbose_name='По первой кафизме седален (б)')),
                ('bg_sed1', models.TextField(verbose_name='Богородичен первого седальна')),
                ('sed2a', models.TextField(verbose_name='По второй кафизме седален (а)')),
                ('sed2b', models.TextField(verbose_name='По второй кафизме седален (б)')),
                ('bg_sed2', models.TextField(verbose_name='Богородичен второго седальна')),
                ('ipac', models.TextField(verbose_name='Ипакои')),
                ('step', models.TextField(verbose_name='Степенна')),
                ('bg_step', models.TextField(verbose_name='Слава, И ныне степенны')),
                ('procimen', models.TextField(verbose_name='Прокимен перед Евангелием')),
                ('st_proc', models.TextField(verbose_name='Стих прокимена')),
                ('kondac', models.TextField(verbose_name='Кондак')),
                ('icos', models.TextField(verbose_name='Икос')),
                ('hv1', models.TextField(verbose_name='Стихира на хвалитех 1')),
                ('hv2', models.TextField(verbose_name='Стихира на хвалитех 2')),
                ('hv3', models.TextField(verbose_name='Стихира на хвалитех 3')),
                ('hv4', models.TextField(verbose_name='Стихира на хвалитех 4')),
                ('hv5', models.TextField(verbose_name='Стихира на хвалитех 5')),
                ('hv6', models.TextField(verbose_name='Стихира на хвалитех 6')),
                ('hv7', models.TextField(verbose_name='Стихира на хвалитех 7')),
                ('hv8', models.TextField(verbose_name='Стихира на хвалитех 8')),
            ],
            options={
                'verbose_name': 'Воскресные службы утреня',
                'verbose_name_plural': 'Воскресные службы утреня',
            },
        ),
        migrations.AddField(
            model_name='sundayservicesvespers',
            name='matins',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='oktoih.sundayservicesvespers'),
        ),
    ]
