# Generated by Django 4.0 on 2022-02-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0004_sundayservicesmatins_sundayservicesvespers_matins'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayservicesmatins',
            name='voice',
            field=models.IntegerField(default=0, verbose_name='Глас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='voice',
            field=models.IntegerField(null=True, verbose_name='Глас'),
        ),
    ]
