# Generated by Django 4.0 on 2022-02-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0005_sundayservicesmatins_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_sed1',
            field=models.TextField(blank=True, verbose_name='Богородичен первого седальна'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_sed2',
            field=models.TextField(blank=True, verbose_name='Богородичен второго седальна'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_step',
            field=models.TextField(blank=True, verbose_name='Слава, И ныне степенны'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_tr',
            field=models.TextField(blank=True, verbose_name='Богородичен тропаря'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv1',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 1'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv2',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 2'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv3',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 3'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv4',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 4'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv5',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 5'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv6',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 6'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv7',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 7'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv8',
            field=models.TextField(blank=True, verbose_name='Стихира на хвалитех 8'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='ipac',
            field=models.TextField(blank=True, verbose_name='Ипакои'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='kondac',
            field=models.TextField(blank=True, verbose_name='Кондак'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='procimen',
            field=models.TextField(blank=True, verbose_name='Прокимен перед Евангелием'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed1a',
            field=models.TextField(blank=True, verbose_name='По первой кафизме седален (а)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed1b',
            field=models.TextField(blank=True, verbose_name='По первой кафизме седален (б)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed2a',
            field=models.TextField(blank=True, verbose_name='По второй кафизме седален (а)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed2b',
            field=models.TextField(blank=True, verbose_name='По второй кафизме седален (б)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='st_proc',
            field=models.TextField(blank=True, verbose_name='Стих прокимена'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='step',
            field=models.TextField(blank=True, verbose_name='Степенна'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='tropar',
            field=models.TextField(blank=True, verbose_name='Тропарь'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='matins',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='oktoih.sundayservicesmatins'),
            preserve_default=False,
        ),
    ]
