# Generated by Django 4.0.2 on 2022-02-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0008_canon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundayservicesvespers',
            name='canon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='oktoih.canon'),
        ),
    ]
