# Generated by Django 4.0.2 on 2022-02-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0009_sundayservicesvespers_canon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SundayTropar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Тропарь воскресный')),
            ],
            options={
                'verbose_name': 'Тропарь воскресный',
                'verbose_name_plural': 'Тропать воскресный',
            },
        ),
        migrations.AddField(
            model_name='sundayservicesvespers',
            name='trvs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oktoih.sundaytropar'),
        ),
    ]
