# Generated by Django 4.0.2 on 2022-02-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0010_sundaytropar_sundayservicesvespers_trvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sundaytropar',
            name='voices',
            field=models.CharField(blank=True, max_length=10, verbose_name='Гласы'),
        ),
    ]
