# Generated by Django 4.0.2 on 2022-02-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0012_evangsunday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canon',
            name='pesn1',
            field=models.TextField(verbose_name='Песнь 1'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='pesn3',
            field=models.TextField(verbose_name='Песнь 3'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='pesn4',
            field=models.TextField(verbose_name='Песнь 4'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='pesn5',
            field=models.TextField(verbose_name='Песнь 5'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='pesn6',
            field=models.TextField(verbose_name='Песнь 6'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='pesn7',
            field=models.TextField(verbose_name='Песнь 7'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='pesn8',
            field=models.TextField(verbose_name='Песнь 8'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='pesn9',
            field=models.TextField(verbose_name='Песнь 9'),
        ),
        migrations.AlterField(
            model_name='canon',
            name='voice',
            field=models.IntegerField(default=0, verbose_name='Глас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evangsunday',
            name='evang',
            field=models.TextField(verbose_name='Евангелие воскресное'),
        ),
        migrations.AlterField(
            model_name='evangsunday',
            name='exapost',
            field=models.TextField(verbose_name='Эксапостиларий'),
        ),
        migrations.AlterField(
            model_name='evangsunday',
            name='st_ev',
            field=models.TextField(verbose_name='Стихира еавнгельская'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_sed1',
            field=models.TextField(verbose_name='Богородичен первого седальна'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_sed2',
            field=models.TextField(verbose_name='Богородичен второго седальна'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_step',
            field=models.TextField(verbose_name='Слава, И ныне степенны'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='bg_tr',
            field=models.TextField(verbose_name='Богородичен тропаря'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv1',
            field=models.TextField(verbose_name='Стихира на хвалитех 1'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv2',
            field=models.TextField(verbose_name='Стихира на хвалитех 2'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv3',
            field=models.TextField(verbose_name='Стихира на хвалитех 3'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv4',
            field=models.TextField(verbose_name='Стихира на хвалитех 4'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv5',
            field=models.TextField(verbose_name='Стихира на хвалитех 5'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv6',
            field=models.TextField(verbose_name='Стихира на хвалитех 6'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv7',
            field=models.TextField(verbose_name='Стихира на хвалитех 7'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='hv8',
            field=models.TextField(verbose_name='Стихира на хвалитех 8'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='ipac',
            field=models.TextField(verbose_name='Ипакои'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='kondac',
            field=models.TextField(verbose_name='Кондак'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='procimen',
            field=models.TextField(verbose_name='Прокимен перед Евангелием'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed1a',
            field=models.TextField(verbose_name='По первой кафизме седален (а)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed1b',
            field=models.TextField(verbose_name='По первой кафизме седален (б)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed2a',
            field=models.TextField(verbose_name='По второй кафизме седален (а)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='sed2b',
            field=models.TextField(verbose_name='По второй кафизме седален (б)'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='st_proc',
            field=models.TextField(verbose_name='Стих прокимена'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='step',
            field=models.TextField(verbose_name='Степенна'),
        ),
        migrations.AlterField(
            model_name='sundayservicesmatins',
            name='tropar',
            field=models.TextField(verbose_name='Тропарь'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='matins',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='oktoih.sundayservicesmatins'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='voice',
            field=models.IntegerField(default='0', verbose_name='Глас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sundaytropar',
            name='text',
            field=models.TextField(verbose_name='Тропарь воскресный'),
        ),
        migrations.AlterField(
            model_name='sundaytropar',
            name='voices',
            field=models.CharField(max_length=10, verbose_name='Гласы'),
        ),
    ]
