# Generated by Django 4.0.2 on 2022-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oktoih', '0013_alter_canon_pesn1_alter_canon_pesn3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='bg_st',
            field=models.TextField(null=True, verbose_name='Богородичен на стиховне'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='dogmatic',
            field=models.TextField(null=True, verbose_name='Догматик'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv1',
            field=models.TextField(null=True, verbose_name='Октоиха 1'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv10',
            field=models.TextField(null=True, verbose_name='Богородице 3'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv2',
            field=models.TextField(null=True, verbose_name='Октоиха 2'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv3',
            field=models.TextField(null=True, verbose_name='Октоиха 3'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv4',
            field=models.TextField(null=True, verbose_name='Анатолиевы 1'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv5',
            field=models.TextField(null=True, verbose_name='Анатолиевы 2'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv6',
            field=models.TextField(null=True, verbose_name='Анатолиевы 3'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv7',
            field=models.TextField(null=True, verbose_name='Анатолиевы 4'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv8',
            field=models.TextField(null=True, verbose_name='Богородице 1'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='gv9',
            field=models.TextField(null=True, verbose_name='Богородице 2'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='st1',
            field=models.TextField(null=True, verbose_name='На стиховне 1'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='st2',
            field=models.TextField(null=True, verbose_name='На стиховне 2'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='st3',
            field=models.TextField(null=True, verbose_name='На стиховне 3'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='st4',
            field=models.TextField(null=True, verbose_name='На стиховне 4'),
        ),
        migrations.AlterField(
            model_name='sundayservicesvespers',
            name='voice',
            field=models.IntegerField(null=True, verbose_name='Глас'),
        ),
    ]
